# Generated by Django 4.0.2 on 2023-09-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0008_post_image_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image_upload',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
